### ISSUE TITLE
What's the differnce between Synergy Branches? (public, dev, twitch)

### ISSUE THREAD

**Issue by arthur4ik** [yarik2720/Synergy-SM#32]
Hi,

afaik twitch branch was made increasing maxplayers to 64.
Are there more differences and which is the recommended branch?
https://steamdb.info/app/17520/depots/

seems that public didn't get any updates anymore?

Thanks!

**Comment by yarik2720** [comment]
Twitch branch is recommended if you want more stability, it have latest crash and performance fixes  that was tested on March Rebel rush.
Also, twitch and develop branches works only on windows (even srcds), while Public works on linux and mac.
Most players are playing on Public branch and can't connect to twitch and develop until they switch their game
