### ISSUE TITLE
Фиксы для dedicated-server версии?

### ISSUE THREAD

**Issue by D13410N3** [yarik2720/Synergy-SM#40]
Нет ли случайно каких-либо фиксов для "серверной" версии? Постоянно ловлю рандомные падения, последнюю карту игра сама не запоминает...
В интернетах вся информация уже давно устарела

**Comment by yarik2720** [comment]
Можно использовать sourcemod плагины отсюда:
https://github.com/Balimbanana/SM-Synergy/tree/master/plugins
crashmap - восстанавливает последнюю карту 
synfixes исправляет множество проблем
synsaverestore также вносит исправления и решает некоторые краши

**Comment by D13410N3** [comment]
После установки sourcemod даже на голую не смог больше вообще к серверу подключиться
Но попробую, спасибо. 

По теме данного репозитория - есть ли смысл накидывать все эти изменённые файлы на steamcmd версию игры?

**Comment by yarik2720** [comment]
Разницы от steamcmd нет
