### ISSUE TITLE
d3_breen_01 Gman Bugs

### ISSUE THREAD

**Issue by marigi64** [yarik2720/Synergy-SM#51]
Gman's speech at the end of hl2 has some issues.

His position doesn't line up with Alyx (due to point_viewcontrol?)

https://user-images.githubusercontent.com/53112738/200099151-5f3fec07-85fd-435d-b54e-894896e661f5.mp4

This part of the speech is messed up completely.
 
https://user-images.githubusercontent.com/53112738/200099386-b5793363-651b-41d6-895b-f38bc3e35021.mp4

**Comment by yarik2720** [comment]
Known issue due to bug in Synergy https://gitlab.com/SynergyMod/Synergy/-/issues/211
