### ISSUE TITLE
Half-Life 2 Synergy issues

### ISSUE THREAD

**Issue by ElvardorSiurn** [yarik2720/Synergy-SM#53]
привет, сэр, сэр, у меня есть некоторые проблемы в Half-Life 2 Synergy с картами, значками и hud
Прежде всего, я начну с проблемы с картой d1_transition 1, у этой карты нет названия Half Life 2 Sense, покажите актерский состав, но в оригинале Half Life 2 он есть.
вот видео моей проблемы и реальное видео халф лайф 2 : 
1 ) Синергия в d1_transition 1 не отображает смысл названия Half-Life 2, показывает : 
[hl2 2023-03-20 17-45-03-589.zip](https://github.com/yarik2720/Synergy-SM/files/11019643/hl2.2023-03-20.17-45-03-589.zip)
-а вот в этом видео вы можете увидеть смысл названия Half-Life 2 : 
[hl2 2023-03-20 17-47-36-736.zip](https://github.com/yarik2720/Synergy-SM/files/11019654/hl2.2023-03-20.17-47-36-736.zip)
-вопрос в том, какой файл я должен редактировать?
или какие файлы мне нужно скопировать и вставить из Half Life 2 Original в Half Life 2 Synergy?
2 ) моя вторая проблема в том, что когда игрок пытается взять костюм, у него нет анимации, например, чтобы увидеть его руки, как выглядит костюм HEV.
это видео от синергии : 
[hl2 2023-03-20 17-56-30-818.zip](https://github.com/yarik2720/Synergy-SM/files/11019703/hl2.2023-03-20.17-56-30-818.zip)
-это второе видео, вы можете увидеть анимацию от взятия хэв костюма :
[hl2 2023-03-20 18-10-17-122.zip](https://github.com/yarik2720/Synergy-SM/files/11019735/hl2.2023-03-20.18-10-17-122.zip)
3 ) 
и мой последний вопрос, как удалить этот значок hud? я знаю файлы hud из
Схема клиента.res
худанимация.txt
hudanimationlayout.txt
i moy pos : 
[problem number 1.zip](https://github.com/yarik2720/Synergy-SM/files/11019766/problem.number.1.zip)
Пожалуйста, помогите мне, если вы можете
Вы очень добры, вы поможете мне и другим игрокам получить удовольствие от игры
Это действительно первый раз, когда я хочу сыграть в сюжетный режим Half Life 2 со своим другом.
Буду очень признателен, если вы решите эти 3 задачи

**Comment by ElvardorSiurn** [comment]
Спасибо тебе друг

**Comment by ElvardorSiurn** [comment]
Кстати, могу ли я запустить Half Life Synergy без Steam с версией Synergy Steam? Я попытался скопировать папку версии Synergy Steam в папку синергии без Steam, и код параметров ланчера, который я увидел, был hl2.exe - steam - игра Synergy -appid 17520 , после того, как я скопировал и вставил, я получил это сообщение об ошибке: Ошибка движка, не удалось загрузить клиент библиотеки, и создадут ли разработчики новую версию синергии?

**Comment by yarik2720** [comment]
Версия без Steam официально не поддерживается

**Comment by ElvardorSiurn** [comment]
@yarik2720 bro , пожалуйста, исправьте ваши отредактированные карты . Когда я хочу начать d2_coast_09 это приводит к сбою моей игры, я не могу запустить свой средний d2_coast_09.edt, а также ваши другие карты аварийно завершает работу моей игры
