### ISSUE TITLE
Add the mission failed screen back

### ISSUE THREAD

**Issue by PossibleReference** [yarik2720/Synergy-SM#54]

**Comment by yarik2720** [comment]
On which map and with which case?

**Comment by PossibleReference** [comment]
On all maps if everyone in the server dies. If Alyx also dies, the screen would appear.

**Comment by yarik2720** [comment]
When every player dies is not controlled by map edits, it is Synergy code. 
When Alyx dies or other main npc's or vehicles - messages will be shown
