### ISSUE TITLE
Правильная установка, таблица смертей, порядок карт Half-Life 2: Update...

### ISSUE THREAD

**Issue by chibinekit** [yarik2720/Synergy-SM#59]
Здравствуйте. Играю на ветке Twitch. Хочу задать несколько вопросов:
0. Всё-таки Twitch и сейчас является наиболее стабильной и актуальной версией? Если я правильно понимаю, [Latest Development Branch и Synergy v20.1 (unreleased)](https://steamdb.info/app/17520/depots/) более новые?
1. Папку SM, содержащую maps и scrtipts из данного сборника следует перекинуть как в Synergy\synergy\custom, так и в Half-Life 2 Update\hl2\custom, чтоб .edt применились к картам Update?
2. Необходимо ли включить опцию Настройки->Дополнительно...->Enable Synergy 'synergy/custom' Folder? Её не сразу включал и всё работало даже без неё, так для чего же она нужна?
3. content_mount_synergy_mod_path_priority 0 необходимо вставлять в консоль при каждом запуске Synergy? Нельзя ли её вставить в Создать сервер->Дополнительно? Я не всегда её вставляю и даже так исправления работают.
4. Можно ли отключить таблицу убийств/смертей справа сверху?
5. [Порядок карт HL2U не такой, как в оригинале](https://imgur.com/a/1OkgJ0T). Из-за этого завершение d1_trainstation_06 приводит к вылету, а не к переходу на d1_canals_01; на d1_town_05 даже в склад не попасть, чтоб закончить уровень, хотя проблем с оригиналом в этих местах нет. Так ведь, что Update должен находиться в Unsupported Content?
6. Почему в этот сборник не включено [исправление GUI](https://steamcommunity.com/sharedfiles/filedetails/?id=2821835774)?
7. Нужно ли для обычной игры (в Update и эпизоды) добавлять что-то из [SourceMod](https://github.com/Balimbanana/SM-Synergy), например то, что Вы рекомендовали?
> synfixes исправляет множество проблем
synsaverestore также вносит исправления и решает некоторые краши
8. Ещё вопрос по MMod: можно ли исправить прицеливание арбалета не отключая autoaim (добавляя к нему лишнюю кавычку, например, чтоб сделать опцию недействительной) в Weapon_crossbow.txt? Ведь тогда прицел не сможет иметь специальной текстуры. Этой проблеме 4 года, судя по обсуждению в [Juniez' Crossbow MMod](https://gamebanana.com/mods/243486), вот цитата:
> Shadow_RUN, 4y
Well ♥♥♥♥, looks like oru favorite game making company just broke custom scopes for the crossbow...
I tested another scope mod that uses a different scope shader (thought that was the issue) - and still the same thing, so either just remove the scope texture entirely, or either wait for them to fix this...
valve i hate you, you break everything that is cool and fun :,c

**Comment by chibinekit** [comment]
Благодарю, но похоже, установка SourceMod совершенно всё меняет, как и в целом использование srcds. Я имею опыт лишь в создании сервера TES3MP, так что сразу извиняюсь за глупые вопросы. Так как изначально Synergy был установлен через обычный клиент Steam'а, bat-ник Syndsinstall не видел Twitch-версию, после установки у меня появилась ещё одна версия игры по пути: "SteamCMD\steamapps\common\syntwitch", первая же - "Steam\steamapps\common\Synergy". Обе Twitch.
Если Вас затруднит мне помочь, пожалуйста, можете ли дать руководства, которые прольют свет на это? Сразу дам вводные: я хочу поиграть с ещё одним человеком в оригинальные части (HL2: Update, Episode One, Episode Two, Lost Coast),  так как у меня серый IP, буду использовать Hamachi для локального соединения.
И так, запуская synergy.exe из syntwitch, меня встречает данная ошибка:
> Error!
> Setupfile 'gameinfo.txt' doesn't exist in subdirectory 'hl2'. Check your -game parameter or VCONFIG setting.
Причём, обычная Steam-версия игры также не запускается напрямую, только через клиент Steam - как же тогда открывать модифицированную версию игры? Иль SourceMod нужен лишь для создания сервера? Если это так, то моему партнёру не нужно устанавливать всё это, ему достаточно присоединиться через установленную обычным способом Synergy версии Twitch?
По пути "SteamCMD\steamapps\common" создался ярлык Half-Life 2 из обычного пути установки, так как он содержит все эпизоды, то всё в порядке, но вопрос в том: почему не создался ярлык папки Half-Life 2 Update? Создание такового ни к чему не приводит. Как же тогда запустить сервер с +map hl2u d1_trainstation_01?
По пути "SteamCMD\steamapps\common\syntwitch\synergy\cfg" находится server2.cfg, установленный bat-ником. Как я понимаю, .bat-файл использует именно данный .cfg при запуске, соответственно, в нём нужно добавить maxplayers 2, что правда изменит максимальное количество игроков с 64 до 2, но map hl2u d1_trainstation_01 по-прежнему не работает, так как консоль не понимает тэг "hl2u" (srcds.exe, запускаемый run.bat, настроенным по [этому руководству](https://steamcommunity.com/sharedfiles/filedetails/?id=359445849), видит HL2: Update, но также не может распознать тэг в "+map hl2u d1_trainstation_01", хотя сам же без него предлагает выбрать hl2 или hl2u.

**Comment by yarik2720** [comment]
Желательно использовать скрипт Syndsinstall, не используйте Twitch версию, она более нестабильна и устаревшая, используйте development версию, скрипт ее установит и обновит при необходимости.
Не используйте hamachi, используйте radmin vpn
К вопросу, что не запускается с параметром `+map hl2u d1_trainstation_01` - возможно проблема с дев версиями, попробуйте запуск обычной public версии
Запуск сервера необходимо производить командной строкой из папки с установленной версией Synergy, например
```srcds.exe -game synergy -console +maxplayers 4+sv_lan 0 +map d1_trainstation_06 +exec server2.cfg -port 27015 -nocrashdialog -timeout 1 -insecure +sv_glow_enable 0`

Последние упомянутые моды и фиксы ставятся только на клиентскую часть, серверу они не нужны.
reUpdate не будет работать с синержи, так как имеет модифицированную клиент-серверную часть, вы просто сломаете мод при установке.

На текущем этапе созданный тикет не имеет больше отношения к данному репозиторию.

Обо всех багах связанных с самой Synergy просьба обращаться на их gitlab: https://gitlab.com/SynergyMod/Synergy/-/issues
