### ISSUE TITLE
New Stable Synergy

### ISSUE THREAD

**Issue by geckotdf** [yarik2720/Synergy-SM#75]
Hi!
In the new stable Synergy I believe the version it's: `23.11`
The way to install this fixes it's:

_Synergy 20.xx (development and twitch branch)_ ?

And finally this part:
set `content_mount_synergy_mod_path_priority 0` for the EDTs to apply.

Where you put that? in the `server.cfg` file?
Thanks!!

**Comment by yarik2720** [comment]
updated readme

**Comment by geckotdf** [comment]
Hi Yarik

set content_mount_synergy_mod_path_priority 0 for the EDTs to apply.

Where you put that? in the server.cfg file?

**Comment by yarik2720** [comment]
yes, you should set this on server config

**Comment by geckotdf** [comment]
Perfect, thanks for the support and efford!
Best regards.
